version: "3.9"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  golang-api:
    image: domih/be-go-ausaestunginfo
    container_name: golang-api
    ports:
      - "8080:8080"
    environment:
      - BE_PORT=8080
      - BE_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - BE_AWS_TABLE_NAME=ausaestungdb
      - BE_AUTH_TENANT_ID=6d52c2eb-75ca-4825-b407-2446c2c43a2d
      - BE_AUTH_CLIENT_ID=dbdc0967-e4b4-4113-8460-f21c691da334
      - BE_AUTH_SCOPE=api://dbdc0967-e4b4-4113-8460-f21c691da334/Access.Api
      - BE_AWS_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
